In [41]:
x = 5 #integer

In [42]:
x

5

In [43]:
type(x)

int

In [44]:
y = 5.0

In [45]:
type(y)

float

In [46]:
z = 'Jordan'

In [47]:
print(z)

Jordan


In [48]:
xx = 'Caroline is 19 years old'

In [49]:
xx

'Caroline is 19 years old'

In [50]:
type(xx)

str

In [51]:
xy = '19'

In [52]:
xy

'19'

In [53]:
float(xy)

19.0

In [54]:
float(xx)

ValueError: could not convert string to float: 'Caroline is 19 years old'

In [55]:
int(xy)

19

In [56]:
int(y)

5

In [57]:
z = 5.9

In [58]:
int(z)

5

In [59]:
test = [1,2,3,4,5]

In [60]:
test

[1, 2, 3, 4, 5]

In [61]:
type(test)

list

In [62]:
test[1]

2

In [63]:
test2 = [1.2,5.4,8.0]

In [64]:
test2

[1.2, 5.4, 8.0]

In [65]:
test2[3]

IndexError: list index out of range

In [66]:
test3 = [0,1,3.4,'this is a test']

In [67]:
test3[1]

1

In [68]:
type(test3[3])

str

In [69]:
test4 = [[3.4,4.5],[1,2,3,4],['this is list', 'jordan', 'caraline']]

In [70]:
test4[0]

[3.4, 4.5]

In [71]:
test4[0][0]

3.4

In [72]:
xx

'Caroline is 19 years old'

In [73]:
xx[0]

'C'

In [74]:
len(xx)

24

In [75]:
xx[0]

'C'

In [76]:
xx[3:5] # slice

'ol'

In [77]:
test

[1, 2, 3, 4, 5]

In [78]:
test[2:5]

[3, 4, 5]

In [79]:
test[2:]

[3, 4, 5]

In [80]:
test[:3]

[1, 2, 3]

In [81]:
test[-2:]

[4, 5]

In [82]:
xx[-3:]

'old'

In [83]:
test

[1, 2, 3, 4, 5]

In [84]:
test2

[1.2, 5.4, 8.0]

In [86]:
test5 = test+test2

In [87]:
test5

[1, 2, 3, 4, 5, 1.2, 5.4, 8.0]

In [88]:
test5 - [1]

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [89]:
test6 = test5+test2

In [90]:
test6

[1, 2, 3, 4, 5, 1.2, 5.4, 8.0, 1.2, 5.4, 8.0]

In [91]:
import numpy as np

In [92]:
test7 = np.array([1,5,8.8,10,12])

In [93]:
test7

array([ 1. ,  5. ,  8.8, 10. , 12. ])

In [94]:
test7[0]

1.0

In [95]:
test7[3:5]

array([10., 12.])

In [96]:
test7[-3:]

array([ 8.8, 10. , 12. ])

In [97]:
test8 = test7 + 1

In [98]:
test8

array([ 2. ,  6. ,  9.8, 11. , 13. ])

In [101]:
test9 = np.array(['test','test2',1,2])

In [102]:
test9

array(['test', 'test2', '1', '2'], dtype='<U5')

In [103]:
test9+1

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U5'), dtype('<U5')) -> dtype('<U5')